Excel_Import/Controllers/ExcelController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

using System.Web.Mvc;
using Dapper;
using DocumentFormat.OpenXml;
using Excel_Import.Models;
using ExcelDataReader;
using GemBox.Spreadsheet;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using MySql.Data.MySqlClient;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Web;
//using OfficeOpenXml;
//using OfficeOpenXml.Style;
//using System.Web.Script.Serialization;
//using DocumentFormat.OpenXml.Spreadsheet;
//using DocumentFormat.OpenXml.Packaging;
using ClosedXML.Excel;

namespace Excel_Import.Controllers
{
    public class ExcelController : Controller
    {
        Contacts obj = new Contacts();
        // GET: Excel     
        public ActionResult Index()
        {
            if (Session["username"] != null && Session["password"] != null)

            {
                return View();
            }
            else
            {
                Response.Redirect("~/Home/Index");
            }
            return View();
        }
        public ActionResult ContactsListView()
        {
            if (Session["username"] != null && Session["password"] != null)
            {
                return View();
            }
            else
            {
                Response.Redirect("~/Home/Index");
            }
            return View();
        }
        static IDbConnection dbExcel = new MySqlConnection(ConfigurationManager.ConnectionStrings["MySqlConnStringExcel"].ConnectionString);

        public JsonResult ContactsListView_Read()

        {
            List<Contacts> _Contacts = new List<Contacts>();
            try
            {
                using (var db = dbExcel)
                {
                    var param = new DynamicParameters();
                    param.Add("ipMode", "GetAll");
                    param.Add("ipContactId", 0);
                    param.Add("ipCompany", null);
                    param.Add("ipLastName", null);
                    param.Add("ipFirstName", null);
                    param.Add("ipTitle", null);
                    param.Add("ipPhone1", null);
                    param.Add("ipPhone2", null);
                    param.Add("ipEmail", null);
                    param.Add("ipAddress", null);
                    param.Add("ipStreet", null);
                    param.Add("ipCity", null);
                    param.Add("ipState", null);
                    param.Add("ipzip", null);
                    param.Add("ipKeywords", null);
                    param.Add("ipCompanyType", null);
                    param.Add("ipPersonType", null);
                    param.Add("outLID", direction: ParameterDirection.Output);

                    using (var mpresults = db.QueryMultiple("contactdetails_crud", param, commandType: System.Data.CommandType.StoredProcedure))
                    {
                        _Contacts = mpresults.Read<Contacts>().ToList();
                        db.Close();
                    }

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ContactsListView_Read => {ex}");
            }
            return Json(_Contacts, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteContact(int a)
        {
            List<Contacts> _Contacts = new List<Contacts>();
            try
            {
                using (var db = dbExcel)
                {
                    var param = new DynamicParameters();
                    param.Add("ipMode", "Delete");
                    param.Add("ipContactId", a);
                    param.Add("ipCompany", null);
                    param.Add("ipLastName", null);
                    param.Add("ipFirstName", null);
                    param.Add("ipTitle", null);
                    param.Add("ipPhone1", null);
                    param.Add("ipPhone2", null);
                    param.Add("ipEmail", null);
                    param.Add("ipAddress", null);
                    param.Add("ipStreet", null);
                    param.Add("ipCity", null);
                    param.Add("ipState", null);
                    param.Add("ipzip", null);
                    param.Add("ipKeywords", null);
                    param.Add("ipCompanyType", null);
                    param.Add("ipPersonType", null);
                    param.Add("outLID", direction: ParameterDirection.Output);

                    using (var mpresults = db.QueryMultiple("contactdetails_crud", param, commandType: System.Data.CommandType.StoredProcedure))
                    {
                        //_Contacts = mpresults.Read<Contacts>().ToList();
                    }

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"DeleteContact => {ex}");
            }
            return Json(_Contacts, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteAdditionalDetails(int id)
        {
            var result = "Failed";
            using (var db = dbExcel)
            {
                var param1 = new DynamicParameters();

                param1.Add("ipMode", "Deleteadditionaldetails");
                param1.Add("ipId", id);
                param1.Add("ipContactId", 0);
                param1.Add("ipColumnName", null);
                param1.Add("ipValue", null);
                param1.Add("ipRowNumber", null);
                param1.Add("outLID", direction: ParameterDirection.Output);
                try
                {
                    var mpresults1 = db.Execute("addtionaldetails_crud", param1, commandType: System.Data.CommandType.StoredProcedure);
                    if (mpresults1 > 0)
                        result = "Success";
                    db.Close();
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"UpdateAdditionalDetails => {ex}");
                }

            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateContact(Contacts obj)
        {
            List<Contacts> _Contacts = new List<Contacts>();
            bool issuccess = false;
            try
            {
                using (var db = dbExcel)
                {

                    var param = new DynamicParameters();
                    param.Add("ipMode", "Update");
                    param.Add("ipContactId", obj.ContactId);
                    param.Add("ipCompany", obj.Company);
                    param.Add("ipLastName", obj.LastName);
                    param.Add("ipFirstName", obj.FirstName);
                    param.Add("ipTitle", obj.Title);
                    param.Add("ipPhone1", obj.Phone1);
                    param.Add("ipPhone2", obj.Phone2);
                    param.Add("ipEmail", obj.Email);
                    param.Add("ipAddress", obj.Address);
                    param.Add("ipStreet", obj.Street);
                    param.Add("ipCity", obj.City);
                    param.Add("ipState", obj.State);
                    param.Add("ipzip", obj.Zip);
                    param.Add("ipKeywords", obj.KeyWords);
                    param.Add("ipCompanyType", obj.CompanyType);
                    param.Add("ipPersonType", obj.PersonType);
                    param.Add("outLID", direction: ParameterDirection.Output);

                    using (var mpresults = db.QueryMultiple("contactdetails_crud", param, commandType: System.Data.CommandType.StoredProcedure))
                    {

                        var id = param.Get<int>("outLID");
                        if (id > 0)
                        {
                            issuccess = true;
                        }
                    }
                }
                if (issuccess)
                    UpdateAdditionalDetails(obj.AdditionalDetails);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"UpdateContact => {ex}");
            }
            return RedirectToAction("ContactsListView");
        }
        public bool UpdateAdditionalDetails(List<AdditionalDetails> additionalDetails)
        {
            bool IsSuccess = false;

            using (var db = dbExcel)
            {
                foreach (var contact in additionalDetails)
                {
                    int additionaldetailsid = 0;
                    var param1 = new DynamicParameters();
                    var addtionaldata = GetAddtionalDetails(contact.ContactId);
                    if (addtionaldata.Count > 0)
                        additionaldetailsid = addtionaldata.Where(x => x.ContactId == contact.ContactId && x.ColumnName.ToLower().Equals(contact.ColumnName.ToLower())).Select(x => x.Id).FirstOrDefault();

                    if (!string.IsNullOrEmpty(contact.ColumnName) && !string.IsNullOrEmpty(contact.ColumnValue) && contact.ContactId != 0)
                    {
                        if (contact.Id == 0 && additionaldetailsid == 0)
                        {
                            param1.Add("ipMode", "InsertAdditionalDetails");
                        }
                        else
                        {
                            param1.Add("ipMode", "Updateaddtionaldetailsbycontactid");
                        }
                        param1.Add("ipId", contact.Id);
                        param1.Add("ipContactId", contact.ContactId);
                        param1.Add("ipColumnName", contact.ColumnName);
                        param1.Add("ipValue", contact.ColumnValue);
                        param1.Add("ipRowNumber", contact.RowNumber);
                        param1.Add("outLID", direction: ParameterDirection.Output);
                        try
                        {

Excel_Import/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendocss")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    <link href="~/Content/Kendo/kendo.default.min.css" rel="stylesheet" />
    <link href="~/Content/Kendo/kendo.common.min.css" rel="stylesheet" />
   
    <style>
        .navbar-inverse {
            background-color: #f0efef;
            border-color: #f0efef;
        }

        .FullWidth {
            width: 95%;
        }
        .navbar-inverse .navbar-nav > li > a {
            color: black;
            font-size: medium;
            font-weight: bold;
        }
            .navbar-inverse .navbar-nav > li > a:hover, .navbar-inverse .navbar-nav > li > a:focus {
                color: #f57024;
                background-color: transparent;
            }
    </style>
</head>


<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Excel Import", "Index", "Excel")</li>
                        <li>@Html.ActionLink("View Contacts", "ContactsListView", "Excel")</li>
                        <li>@Html.ActionLink("Logout","Index","Home")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content FullWidth">
        @RenderBody()
       
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    <script src="~/Scripts/jquery.loadingModal.min.js"></script>
    @*<script src="~/Scripts/Kendo/kendo.all.min.js"></script>*@
    @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
    @RenderSection("scripts", required: false)

</body>
</html>